-- MySQL Script generated by MySQL Workbench
-- Sun Mar  5 15:25:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema plug
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema plug
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `plug` DEFAULT CHARACTER SET utf8 ;
USE `plug` ;

-- -----------------------------------------------------
-- Table `plug`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plug`.`user` (
  `id` INT UNSIGNED NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  UNIQUE INDEX `Username_UNIQUE` (`username` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plug`.`playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plug`.`playlist` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Playlist_User1_idx` (`user_id` ASC) ,
  CONSTRAINT `fk_Playlist_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `plug`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plug`.`song`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plug`.`song` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `lenght` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idSong_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plug`.`playlist_has_song`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plug`.`playlist_has_song` (
  `playlist_id` INT UNSIGNED NOT NULL,
  `song_id` INT UNSIGNED NOT NULL,
  `count` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`playlist_id`, `song_id`),
  INDEX `fk_Playlist_has_Song_Song1_idx` (`song_id` ASC) ,
  INDEX `fk_Playlist_has_Song_Playlist1_idx` (`playlist_id` ASC) ,
  CONSTRAINT `fk_Playlist_has_Song_Playlist1`
    FOREIGN KEY (`playlist_id`)
    REFERENCES `plug`.`playlist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Playlist_has_Song_Song1`
    FOREIGN KEY (`song_id`)
    REFERENCES `plug`.`song` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
