-- MySQL Script generated by MySQL Workbench
-- Sun Mar  5 17:43:14 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tempplaylist
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tempplaylist
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tempplaylist` DEFAULT CHARACTER SET utf8 ;
USE `tempplaylist` ;

-- -----------------------------------------------------
-- Table `tempplaylist`.`song`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tempplaylist`.`song` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `length` INT UNSIGNED NOT NULL,
  `queue` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idsong_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;

USE `tempplaylist`;

DELIMITER $$
USE `tempplaylist`$$
CREATE DEFINER = CURRENT_USER TRIGGER `tempplaylist`.`song_AFTER_DELETE` AFTER DELETE ON `song` FOR EACH ROW
BEGIN
	update song.queue set queue = queue - 1;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
